name: Check-in Backend
version: "1.0"
slug: checkin
description: Vendég check-in backend FastAPI-val
startup: application
boot: auto
host_network: true
arch:
  - aarch64
  - amd64
options: {}
schema: {}
